_wandb:
    value:
        cli_version: 0.23.0
        e:
            6u2cal0qif3g6wcwr9n406ec5jrshewu:
                codePath: scripts\train_2d.py
                codePathLocal: scripts\train_2d.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "524287995904"
                        used: "266969702400"
                email: 2534172@tongji.edu.cn
                executable: E:\mssb\project\.venv\Scripts\python.exe
                git:
                    commit: b504c25830e5403e61f0d1a5c543a57075aa32b9
                    remote: https://github.com/rubiasnow12/ACDC.git
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-5cfd11f1-869f-97a9-93ba-aa0f1660e0dc
                host: DESKTOP-EEEEIBT
                memory:
                    total: "16964685824"
                os: Windows-10-10.0.26220-SP0
                program: E:\mssb\project\scripts\train_2d.py
                python: CPython 3.9.21
                root: E:\mssb\project
                startedAt: "2025-11-24T12:55:28.637194Z"
                writerId: 6u2cal0qif3g6wcwr9n406ec5jrshewu
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 48
                - 53
            "2":
                - 1
                - 5
                - 9
                - 41
                - 48
                - 53
            "3":
                - 7
                - 13
                - 16
                - 66
            "4": 3.9.21
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 10
dropout:
    value: 0.3
fold:
    value: 1
learning_rate:
    value: 0.0005000000237487257
